server:
  address: 0.0.0.0
  port: 8087
  timeout:
    idle: 60
    read: 15
    write: 15
database:
  postgres:
    host: localhost
    dbname: postgres
    port: 5432
    user: postgres
    sslmode: disable
  mysql:
    host: localhost
    db: testdb
    port: 3306
    user: user
    password: password
